---
- name: VM Build Block terraform
  block:
        - name: Create terraform workspace directory
          file:
            dest: "{{tf_build_dir}}"
            state: directory
        
        - name: Download main.tf and terraform.tfstate file
          get_url:
            url: "https://{{vcenter_hostname}}/folder/{{tf_files_folder}}/{{item}}?dcPath={{dc}}&dsName={{datastore}}"
            dest: "{{tf_build_dir}}/{{item}}"
            username: "{{vcenter_username}}"
            password: "{{vcenter_password}}"
            force_basic_auth: yes
            validate_certs: False
          delegate_to: localhost
          with_items:
               - "main.tf"
               - "terraform.tfstate"
          ignore_errors: True         

        - name: Decom servers 
          blockinfile:
                     path: "{{tf_build_dir}}/main.tf"
                     marker: "# {{item.server_name}} {mark}"
                     state: absent
          #when: delete_server|bool
          loop: "{{instance}}"
          ignore_errors: True

        - name: Terraform init 
          shell: terraform init
          args:
            chdir: "{{tf_build_dir}}"

        - name: Terraform plan 
          shell: terraform plan 
          args:
            chdir: "{{tf_build_dir}}"

        - name: Terraform apply
          shell: terraform apply --auto-approve
          args:
            chdir: "{{tf_build_dir}}"


        - name: Copy main.tf and terraform.tfstate files to datastore on vcenter_hostname server
          community.vmware.vsphere_copy:
            hostname: '{{vcenter_hostname}}'
            username: '{{vcenter_username}}'
            password: '{{vcenter_password}}'
            src: "{{tf_build_dir}}/{{item}}"
            datacenter: "{{dc}}"
            datastore: "{{datastore}}"
            path: "{{tf_files_folder}}/{{item}}"
            validate_certs: False
          delegate_to: localhost
          with_items:
               - "main.tf"
               - "terraform.tfstate"
  when: provisioning_type == "automated"


- name: VM Build Block - manual
  block:
        - name: Delete VM from vCenter
          vmware_guest:
            hostname: '{{vcenter_hostname}}'
            username: '{{vcenter_username}}'
            password: '{{vcenter_password}}'
            validate_certs: False
            datacenter: "{{dc}}"
            name: "{{item.server_name}}"
            state: absent
            force: yes
          delegate_to: localhost
          loop: "{{instance}}"
  when: provisioning_type == "manual"
